<a href="https://colab.research.google.com/github/niravrupapara/Pytorch/blob/main/dataset_and_dataloder_demo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from sklearn.datasets import make_classification
import torch

In [3]:
X, y = make_classification(
    n_samples=10,       # Number of samples
    n_features=2,       # Number of features
    n_informative=2,    # Number of informative features
    n_redundant=0,      # Number of redundant features
    n_classes=2,        # Number of classes
    random_state=42     # For reproducibility
)

In [4]:
X

array([[ 1.06833894, -0.97007347],
       [-1.14021544, -0.83879234],
       [-2.8953973 ,  1.97686236],
       [-0.72063436, -0.96059253],
       [-1.96287438, -0.99225135],
       [-0.9382051 , -0.54304815],
       [ 1.72725924, -1.18582677],
       [ 1.77736657,  1.51157598],
       [ 1.89969252,  0.83444483],
       [-0.58723065, -1.97171753]])

In [5]:
y

array([1, 0, 0, 0, 0, 1, 1, 1, 1, 0])

In [7]:
print("shape of input", X.shape)
print("shape of output", y.shape)

shape of input (10, 2)
shape of output (10,)


In [8]:
X = torch.from_numpy(X)
y = torch.from_numpy(y)

In [10]:
print(X.shape)

torch.Size([10, 2])


In [11]:
from torch.utils.data import Dataset , DataLoader

In [12]:
class CustomDataset(Dataset):
    def __init__(self, features, labels):
      self.features = features
      self.labels = labels

    def __len__(self):
      return self.features.shape[0]

    def __getitem__(self, idx):
      return self.features[idx], self.labels[idx]

In [13]:
dataset = CustomDataset(X, y)

In [14]:
len(dataset)

10

In [15]:
dataset[2]

(tensor([-2.8954,  1.9769], dtype=torch.float64), tensor(0))

In [16]:
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)

In [17]:
for batch_feature , batch_label in dataloader:
  print("batch feature", batch_feature)
  print("batch label", batch_label)
  print("--"*20)

batch feature tensor([[ 1.8997,  0.8344],
        [-0.7206, -0.9606]], dtype=torch.float64)
batch label tensor([1, 0])
----------------------------------------
batch feature tensor([[ 1.0683, -0.9701],
        [-0.5872, -1.9717]], dtype=torch.float64)
batch label tensor([1, 0])
----------------------------------------
batch feature tensor([[-1.1402, -0.8388],
        [ 1.7774,  1.5116]], dtype=torch.float64)
batch label tensor([0, 1])
----------------------------------------
batch feature tensor([[ 1.7273, -1.1858],
        [-0.9382, -0.5430]], dtype=torch.float64)
batch label tensor([1, 1])
----------------------------------------
batch feature tensor([[-1.9629, -0.9923],
        [-2.8954,  1.9769]], dtype=torch.float64)
batch label tensor([0, 0])
----------------------------------------
