In [5]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [6]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')


In [8]:
df.head()

id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
0    842302         M  ...                  0.11890          NaN
1    842517         M  ...                  0.08902          NaN
2  84300903         M  ...                  0.08758          NaN
3  84348301         M  ...                  0.17300          NaN
4  84358402         M  ...                  0.07678          NaN

[5 rows x 33 columns]

In [9]:
df.shape

(569, 33)

In [10]:
df.drop(columns=['id' , 'Unnamed: 32'], inplace=True)

In [11]:
df.head()

diagnosis  radius_mean  ...  symmetry_worst  fractal_dimension_worst
0         M        17.99  ...          0.4601                  0.11890
1         M        20.57  ...          0.2750                  0.08902
2         M        19.69  ...          0.3613                  0.08758
3         M        11.42  ...          0.6638                  0.17300
4         M        20.29  ...          0.2364                  0.07678

[5 rows x 31 columns]

In [12]:
df.shape

(569, 31)

In [13]:
X_train , X_test , y_train , y_test = train_test_split(df.iloc[:,1:] , df.iloc[:,0], test_size=0.2)

In [14]:
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [15]:
X_train

array([[-0.37058595, -0.20412389, -0.32663994, ..., -0.08998276,
        -0.52462898,  0.25608228],
       [-0.8336381 , -1.03640145, -0.86534796, ..., -1.5104246 ,
        -0.15443841, -0.55750224],
       [-1.35776769,  0.63783132, -1.35088586, ..., -1.18897952,
        -0.06387677, -0.06879994],
       ...,
       [-0.16320676,  1.4313983 , -0.17825824, ...,  0.04452589,
        -0.41500173, -0.56908548],
       [-0.19161487, -0.04202332, -0.17619738, ...,  0.45569436,
        -0.39116972, -0.40967807],
       [ 1.78558942,  0.38863193,  1.74452132, ...,  0.70025553,
         0.48902587, -1.12673562]])

In [16]:
y_train

518    B
333    B
416    B
528    B
242    B
      ..
216    B
93     B
100    M
396    B
533    M
Name: diagnosis, Length: 455, dtype: object

In [17]:
y_train

518    B
333    B
416    B
528    B
242    B
      ..
216    B
93     B
100    M
396    B
533    M
Name: diagnosis, Length: 455, dtype: object

In [18]:
encoder = LabelEncoder()

y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [19]:
y_train

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0,

In [21]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)

y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [22]:
X_train_tensor.shape

torch.Size([455, 30])

In [23]:
y_train_tensor.shape

torch.Size([455])

DEFINING THE  MODEL

In [32]:
class MySimpleNN():
    def __init__(self, X):
        self.weights = torch.rand(X.shape[1], 1, dtype=torch.float64, requires_grad=True)
        self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

    def forward(self, X):
        z = torch.matmul(X, self.weights) + self.bias 
        y_pred = torch.sigmoid(z)
        return y_pred

    def loss_function(self, y_pred, y):
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred, epsilon,  1-epsilon)

        loss = -(y_train_tensor*torch.log(y_pred) + (1-y_train_tensor)* torch.log(1-y_pred)).mean()      
        return loss

In [33]:
learning_rate = 0.1
epochs = 25

In [35]:
model = MySimpleNN(X_train_tensor)

for epoch in range(epochs):
    y_pred = model.forward(X_train_tensor)

    loss = model.loss_function(y_pred, y_train_tensor)

    loss.backward()
    
    
    with torch.no_grad():
        model.weights -= learning_rate*model.weights.grad
        model.bias -= learning_rate*model.bias.grad

    model.weights.grad.zero_()
    model.bias.grad.zero_()

    print(f'Epoch: {epoch+1} , loss: {loss.item()}')
    

Epoch: 1 , loss: 3.5085050386704184
Epoch: 2 , loss: 3.376911849568895
Epoch: 3 , loss: 3.2424172994811955
Epoch: 4 , loss: 3.10332120678626
Epoch: 5 , loss: 2.961599448782194
Epoch: 6 , loss: 2.8170089942453194
Epoch: 7 , loss: 2.6729125792867223
Epoch: 8 , loss: 2.5248388944396862
Epoch: 9 , loss: 2.363472849087912
Epoch: 10 , loss: 2.2057632909049314
Epoch: 11 , loss: 2.050259282928211
Epoch: 12 , loss: 1.8887194424449492
Epoch: 13 , loss: 1.7340220318263857
Epoch: 14 , loss: 1.5862782116802105
Epoch: 15 , loss: 1.4480054810690608
Epoch: 16 , loss: 1.3197918444399148
Epoch: 17 , loss: 1.206108571108395
Epoch: 18 , loss: 1.108220056962844
Epoch: 19 , loss: 1.0266407793574084
Epoch: 20 , loss: 0.9608657045573893
Epoch: 21 , loss: 0.9093640554653727
Epoch: 22 , loss: 0.8698746981753358
Epoch: 23 , loss: 0.8398697390881867
Epoch: 24 , loss: 0.8169861153554799
Epoch: 25 , loss: 0.7992862757374847


In [37]:
model.bias

tensor([-0.1452], dtype=torch.float64, requires_grad=True)

Evaluation

In [54]:
with torch.no_grad():
    y_pred = model.forward(X_test_tensor)
    y_pred = (y_pred > 0.6).float()
    
    accuracy = (y_pred == y_test_tensor).float().mean()

    print(f"Accuracy: {accuracy.item()}")
    

Accuracy: 0.59602952003479
