<a href="https://colab.research.google.com/github/niravrupapara/Pytorch/blob/main/pytorch_training_pipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import torch.nn as nn

In [11]:
class Model(nn.Module):

  def __init__(self, num_features):
    super(Model, self).__init__()

    self.network = nn.Sequential(
      nn.Linear(num_features, 3),
      nn.ReLU(),
      nn.Linear(3,1),
      nn.Sigmoid()
    )

  def forward(self, features):
    output = self.network(features)
    return output

In [12]:
features = torch.rand(10, 5)

model = Model(features.shape[1])


model(features)

tensor([[0.3785],
        [0.3981],
        [0.3847],
        [0.3802],
        [0.4073],
        [0.3573],
        [0.3981],
        [0.4000],
        [0.3989],
        [0.3602]], grad_fn=<SigmoidBackward0>)

In [19]:
model.network[0]

Linear(in_features=5, out_features=3, bias=True)

In [20]:
model.network[0].weight

Parameter containing:
tensor([[-0.1816, -0.1158,  0.1923, -0.0193, -0.0378],
        [ 0.0837, -0.1441,  0.1388,  0.3341,  0.2623],
        [-0.1234,  0.1436, -0.1957,  0.2753,  0.2417]], requires_grad=True)

In [21]:
model.network[0].bias

Parameter containing:
tensor([ 0.3260, -0.2820,  0.2071], requires_grad=True)

VISUALIZE

In [22]:
!pip install torchinfo

In [23]:
from torchinfo import summary

summary(model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00